### ISSUE TITLE
Extremely confused

### ISSUE THREAD

**Issue by dvershinin** [Jas0n99/ngx_force_gunzip_module#1]
Quoting some README stuff:

> This is a simple patch modifying the NGINX gunzip filter module to force **inflate** compressed responses.

The gunzip module *deflates* responses, not inflates. I think you got the wording wrong from the author, who is, AFAIK, a Chinese native speaker.

> It greatly reduces network bandwidth between nginx and upstream server(s).

How? It doesn't say, but I guess you *have to* enforce compression by always sending `Accept-Encoding: gzip` to the upstream, e.g. `proxy_set_header Accept-Encoding "gzip";`. There is no mention of that in the README at all. Instead, there's a suggestion to comment/remove `proxy_set_header Accept-Encoding "";`. With this commented, the result would be that some requests are (depending on the client's `Accept-Encoding`) will be compressed by the upstream, and some not.

> I set my upstream server to use gzip level 1 to maximize speed since nginx will recompress the content (typically with brotli).

Something like [this](https://github.com/google/ngx_brotli/issues/76) would allow unbrotli upstream requests and you wouldn't have to do double compression. (wouldn't work with this patch, I guess).

**Comment by Jas0n99** [comment]
_Deflate_ is when the data is compressed (think like when a balloon deflates, it shrinks). _Inflate_ is when it is de-compressed back to it's original state.

gzip = deflates
gunzip = inflates

I left `proxy_set_header Accept-Encoding...` commented out, and like you said nginx just passes the clients preferences. You could override and always send gzip I guess, but honestly the amount of clients that don't use compression are probably a fraction of a percent so while _you are technically correct_ I don't think there would be any noticeable bandwidth difference.

My upstream server doesn't do brotli compression, only gzip. But yes that other module you linked could probably be tweaked to do similar.

Depending on what modules / filters you use, _some can not manipulate compressed content from upstream_. The official nginx solution is to just have all transfers uncompressed between the proxy & upstream (via `proxy_set_header Accept-Encoding "";`) but like I mentioned that can be a huge waste of bandwidth (depending on the content). While it might seem somewhat inefficient to do `upstream->compress->send to nginx->decompress->do whatever->recompress->send to client`  from my testing it actually worked out considerably better.

This patch (or more like a hack) I put up on GH mostly just for my personal archival so it wouldn't get lost over time, but I figure there are some others out there that might find it useful. It was just blind luck finding the original author's post after doing a ton of searching.

I'm not trying to support or develop this in any way, I figure if someone finds this patch and knows what it is, they would have the technical knowledge to know what they are doing and how to implement it. It's just a work-around until the day nginx actually implements similar (a to-do has been sitting as a comment in the module code for years).

Hope that answers your questions?

**Comment by dvershinin** [comment]
Yes, thank you :-)  inflate/deflate - something I must remember.

**Comment by G2G2G2G** [comment]
It has been years since, but just so you know @dvershinin in that thread you linked you are not following it but some guy did make an unbrotli module and posted it there
https://github.com/clyfish/ngx_unbrotli
